# @package _global_
method_name: nash_mtl

method:
  name: nash_mtl

module:
  engine:
    _target_: spectra.engine.optimizers.NashMTLEngine
    debug: false
    debug_interval: 10
    debug_max_steps: 10
    debug_full_matrix: false

train:
  grad_clip: 1.0
